PreCommit:
  RuboCop:
    enabled: true
    auto_correct: true
    on_warn: fail # Treat all warnings as failures

  Flay:
    enabled: true
    include:
     - 'lib/ruby_llm/**/*.rb'
    exclude:
     - 'lib/ruby_llm/providers/**/*.rb'
     - 'lib/ruby_llm/active_record/acts_as_legacy.rb'
    mass_threshold: 70

  RSpec:
    enabled: true
    command: [
      'bundle', 'exec', 'bin/rspec-queue',
      '--tag', '~generator'
    ]
    on_warn: fail

  TrailingWhitespace:
    enabled: true
    auto_correct: true
    exclude:
     - '**/db/structure.sql' # Ignore trailing whitespace in generated files


  AppraisalUpdate:
    enabled: true
    description: 'Update appraisal gemfiles'
    command: ['bundle', 'exec', 'appraisal', 'update']

  Gitleaks:
    enabled: true
    required_executable: 'gitleaks'
    command: ['bin/gitleaks-staged']

PostCheckout:
  ALL: # Special hook name that customizes all hooks of this type
    quiet: true # Change all post-checkout hooks to only display output on failure

  IndexTags:
    enabled: true # Generate a tags file with `ctags` each time HEAD changes
